# Generated by Django 5.1.7 on 2025-03-22 07:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, choices=[('Deposit', 'Deposit')], max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Checking', 'Checking')], max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(blank=True, default='PHP', max_length=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Frozen', 'Frozen'), ('Closed', 'Closed')], default='Active', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
        ),
    ]
