# Generated by Django 5.1.7 on 2025-04-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_status_account_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='product',
        ),
    ]
