# Generated by Django 5.1.7 on 2025-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='product',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
