# Generated by Django 5.1.7 on 2025-04-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
