# Generated by Django 5.1.7 on 2025-03-23 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_account_status_account_is_active'),
        ('cards', '0002_alter_card_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_accounts', to='cards.card')),
            ],
        ),
    ]
