# Generated by Django 5.1.7 on 2025-04-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_account_status_account_is_active'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ATM Deposit', 'ATM Deposit'), ('ATM Withdrawal', 'ATM Withdrawal'), ('Fund Transfer', 'Fund Transfer')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(blank=True, default='PHP', max_length=5)),
                ('description', models.TextField()),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_owner', to='accounts.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='accounts.account')),
            ],
        ),
    ]
