# Generated by Django 5.1.7 on 2025-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ATM Deposit', 'ATM Deposit'), ('ATM Withdrawal', 'ATM Withdrawal'), ('Fund Transfer', 'Fund Transfer'), ('Initial Deposit', 'Initial Deposit'), ('Account Creation Deduction', 'Account Creation Deduction')], max_length=50),
        ),
    ]
