# Generated by Django 5.1.7 on 2025-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('ATM Deposit', 'ATM Deposit'), ('ATM Withdrawal', 'ATM Withdrawal'), ('Fund Transfer', 'Fund Transfer')], max_length=50),
        ),
    ]
