# Generated by Django 5.1.7 on 2025-03-22 07:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=16, unique=True)),
                ('card_pin', models.CharField(blank=True, max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('card_type', models.CharField(blank=True, choices=[('Debit', 'Debit')], max_length=10)),
                ('card_cvv', models.CharField(blank=True, max_length=4, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Active', max_length=10)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
