# Generated by Django 5.1.7 on 2025-03-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Blocked', 'Blocked'), ('Pending', 'Pending'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Active', 'Active')], default='Active', max_length=10),
        ),
    ]
